server:
  port: 5000


spring:
#  config:
#    import : "optional:aws-parameterstore:/config/taco_3_team1_be/deploy/"
  profiles:
    active: prod
  servlet:
    multipart:
      max-file-size: 300MB
      max-request-size: 300MB



cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    region:
      static: ${AWS_REGION}
    stack:
      auto: false
#    parameter-store:
#      enabled: true
#      prefix : /config/taco_3_team1_be/deploy
#      name : taco_3_team1_be/deploy


openai:
    api:
      key: ${OPENAI_API_KEY}
      base-url: https://api.openai.com/v1/chat/completions
      model: gpt-4o
      max-tokens: 5000
      temperature: 0.7

logging:
  level:
    root: INFO
    com.taco1.demo: DEBUG
  file:
    name: logs/application.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"




---

spring:
  config:
    activate:
      on-profile: local
#  datasource:
#    url: jdbc:mysql://your-rds-endpoint:3306/your-db-name
#    username: admin
#    password: tacobackend
#    driver-class-name: com.mysql.cj.jdbc.Driver
#
#  jpa:
#    hibernate:
#      ddl-auto: update  # 주의: 운영 환경에서는 validate 권장
#    show-sql: false
#    database-platform: org.hibernate.dialect.MySQLDialect
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQLDialect



  redis:
    #host: taco-3-team1-diary-redis-7f0usp.serverless.apn2.cache.amazonaws.com
    host : localhost
    port: 6379 #6379
    ssl: false
    password :

#  datasource:
#    url: jdbc:mysql://your-cloud-url:3306/your-db
#    username: your-username
#    password: your-password
#    driver-class-name: com.mysql.cj.jdbc.Driver
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    database-platform: org.hibernate.dialect.MySQL8Dialect

---

spring:
  config:
    activate:
      on-profile: prod
  redis:
    host: taco3-team1-redis.7f0usp.ng.0001.apn2.cache.amazonaws.com
    port: 6379
    ssl: false
    password:

---



spring:
  config:
    activate:
      on-profile: test

  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password: sa

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true
